autojob:
  normalization:
    taxonomy:
      location:

        ignored-values:
          - not available
          - n/a
          - unknown

        aliases:

          - canonical: "Hồ Chí Minh"
            aliases:
              - TP.HCM
              - TP HCM
              - TPHCM
              - HCM
              - HCMC
              - Hồ Chí Minh
              - Thành phố Hồ Chí Minh
              - Ho Chi Minh
              - Ho Chi Minh City
              - Sai Gon
              - Sài Gòn
              - Saigon

          - canonical: "Hà Nội"
            aliases:
              - HN
              - Hà Nội
              - Ha Noi
              - Hanoi
              - Thành phố Hà Nội

          - canonical: "Đà Nẵng"
            aliases:
              - Đà Nẵng
              - Da Nang
              - Danang

          - canonical: "Remote"
            aliases:
              - Remote
              - Work from home
              - WFH
              - Từ xa
              - Làm việc từ xa

          - canonical: "Bình Dương"
            aliases:
              - Bình Dương
              - Binh Duong

          - canonical: "Bắc Ninh"
            aliases:
              - Bắc Ninh
              - Bac Ninh

          - canonical: "Hải Phòng"
            aliases:
              - Hải Phòng
              - Hai Phong

          - canonical: "Quảng Ninh"
            aliases:
              - Quảng Ninh
              - Quang Ninh

          - canonical: "Đồng Nai"
            aliases:
              - Đồng Nai
              - Dong Nai

          - canonical: "Cần Thơ"
            aliases:
              - Cần Thơ
              - Can Tho

          - canonical: "Long An"
            aliases:
              - Long An

          - canonical: "Bà Rịa - Vũng Tàu"
            aliases:
              - Bà Rịa - Vũng Tàu
              - Ba Ria - Vung Tau
              - Bà Rịa Vũng Tàu
              - Ba Ria Vung Tau

          - canonical: "Tây Ninh"
            aliases:
              - Tây Ninh
              - Tay Ninh

          - canonical: "Gia Lai"
            aliases:
              - Gia Lai

          - canonical: "Khánh Hòa"
            aliases:
              - Khánh Hòa
              - Khanh Hoa

          - canonical: "Huế"
            aliases:
              - Huế
              - Hue
              - Thừa Thiên Huế
              - Thua Thien Hue